template = "https://github.com/giellalt/template-lang-und"
rev_id = 340
template_sha = "1186578fa79468b8b3349a52ce4880edc3ce8803"

[replacements]
__GLOTTOLOG_ID__ = "lush1252"
__REPO__ = "lang-lut"
__UND2C__ = "lut"
__UNDEFINED__ = "Lushootseed"
__UND__ = "lut"
