[package]
name = "lut"
human_name = "Lushootseed"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.lut]
filename = "lut-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-lut"
platform = "windows"
uuid = "C0B82416-75EA-4A07-9D91-31FB54C4CC8F"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.lut"
package = "speller-lut"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-lut-mso"
platform = "windows"
uuid = "ACBE88DA-24D5-4910-BF34-CC482D137ADB"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-lut"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
